name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Welcome to the AMS community. Thanks for raising an issue. Make sure to use give a proper description and a way to reproduce the bug."
        pr-message: "Welcome to the AMS community. Thanks for the PR. I'll review it soon."
